services:
  app:
    container_name: wechat_rails_app
    build: ..
    ports:
      # 默认的
      - "41234:80"
    volumes: # 这里的挂在路径注意一下
      - ./config/database.yml:/rails/config/database.yml
      - ./config/wechat_api.yml:/rails/config/wechat_api.yml
      - ./config/seeds.rb:/rails/db/seeds.rb
      - ../storage:/rails/storage
    environment:
      - RAILS_MAX_THREADS=10
      - SECRET_KEY_BASE
      - RAILS_MASTER_KEY
      - RAILS_MASTER_KEY_FILE
      - RAILS_CREDENTIALS_YML_ENC_BASE64
      - RAILS_CREDENTIALS_YML_ENC_FILE
      - RUN_DB_MERGE_SCRIPT=${RUN_DB_MERGE_SCRIPT:-0}
      - DB_MERGE_SCRIPT_PATH=${DB_MERGE_SCRIPT_PATH:-/rails/bin/db-merge}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: wechat-rails-redis
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # 数据库，如果你已经有 PG了，可以注释掉，记得配置好数据库密码
#  db:
#    container_name: wechat_rails_db
#    image: groonga/pgroonga:4.0.6-alpine-17
#    volumes:
#      # 挂载位置 记得修改
#      - ./db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_PASSWORD: password # 记得修改
#      POSTGRES_USER: wechat_rails # 记得修改
#      POSTGRES_DB: wechat_rails
#      PGDAT: /var/lib/postgresql/data/pgdata
