# 这是微信服务的配置
appname = wxapi
httpaddr = "0.0.0.0"
# 程序使用的主端口
httpport = 8059
runmode = prod
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true

# redis 配置，这里的名称是使用 docker 能访问的地址，如果你已经有 Redis 需要注意使用容器能访问到的地址
redislink = wechat-rails-redis:6379
redispass = ""
redisdbnum = 1


syncmessage = true
msgpush = false
# 收到消息后主动请求的地址（861 会携带消息内容，861 之前的没有携带消息内容），需要能访问到的地址（你的微信服务容器内能访问到的地址）
syncmessagebusinessuri = "http://wechat-rails-app/message/callback/{0}"
logoutbusinessuri = ""

sessionon = true

SessionName = "wxapi"
ServerName = "wxapi"

longlinkenabled = true
longlinkconnecttimeout = "30m"

# mq 暂时没实现不需要了
rabbitmq = false
rabbitmqurl = "amqp://guest:guest@10.10.11.7:5672/"
rabbitmqexchange = "wxapi"

ocrurl = ""


