default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  # 这里是读的环境变量，后面是 兜底
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "wechat_rails") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "wechat-rails-db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

production:
  primary: &primary_production
    <<: *default
    database: wechat_rails_production
  cache:
    <<: *primary_production
    database: wechat_rails_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: wechat_rails_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: wechat_rails_production_cable
    migrations_paths: db/cable_migrate
  notify:
    <<: *default
    database: wechat_rails_production
    poll: 10
