default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: wechat_rails
  password: password
  host: wechat-rails-db
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: wechat_rails
  cache:
    <<: *primary_production
    database: wechat_rails_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: wechat_rails_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: wechat_rails_cable
    migrations_paths: db/cable_migrate
  notify:
    <<: *default
    database: wechat_rails
    poll: 10
