# config/wechat_api.yml
default: &default
  base_url: 'http://10.0.0.230:8059/api'
  callback_url: 'http://10.0.0.198:33000/message/callback/{0}'
  timeout: 10
  retry_count: 3

production:
  <<: *default
