# config/wechat_api.yml
default: &default
  # 微信协议地址
  base_url: 'http://wechat-rails-app:8059/api'
  # 这里写你的 微信协议能访问到的地址和端口, 这里和上面的微信服务配置是一样的
  callback_url: 'http://wechat-rails-app/message/callback/{0}'
  timeout: 10
  retry_count: 3

production:
  <<: *default
