# config/wechat_api.yml
default: &default
  base_url: 'https://192.168.110.185:8059/api'
  callback_url: 'http://192.168.110.185:33000/message/callback/{0}'
  timeout: 10
  retry_count: 3

production:
  <<: *default