default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: wechat_rails
  password: wechat_rails_password
  host: 203.0.113.10
  port: 45001

development:
  primary:
    <<: *default
    database: wechat_rails_development

test:
  <<: *default
  database: wechat_rails_test

production:
  primary: &primary_production
    <<: *default
    database: wechat_rails
  cache:
    <<: *primary_production
    database: wechat_rails_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: wechat_rails_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: wechat_rails_cable
    migrations_paths: db/cable_migrate
