# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/utils", under: "utils"
pin "@rails/actioncable", to: "actioncable.esm.js"
pin "codemirror", to: "https://esm.sh/codemirror@6.0.2"
pin "@codemirror/autocomplete", to: "https://esm.sh/@codemirror/autocomplete@6.18.6"
pin "@codemirror/commands", to: "https://esm.sh/@codemirror/commands@6.8.1"
pin "@codemirror/lang-javascript", to: "https://esm.sh/@codemirror/lang-javascript@6.2.5"
pin "@codemirror/state", to: "https://esm.sh/@codemirror/state@6.5.2"
pin "@codemirror/theme-one-dark", to: "https://esm.sh/@codemirror/theme-one-dark@6.1.3"
pin "@codemirror/view", to: "https://esm.sh/@codemirror/view@6.36.5"
pin "prettier/standalone", to: "https://esm.sh/prettier@3.5.3/standalone"
pin "prettier/plugins/babel", to: "https://esm.sh/prettier@3.5.3/plugins/babel"
pin "prettier/plugins/estree", to: "https://esm.sh/prettier@3.5.3/plugins/estree"
