name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Use the standard checkout action
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 获取当前的 git tag 作为版本号
      - name: Get current tag
        id: get_tag
        run: echo "TAG=$(echo ${GITHUB_REF} | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      # 确保在仓库目录下执行 git fetch 和 git tag
      - name: Fetch and set latest tag
        run: |
          git fetch --tags
          git tag -f latest

      # Convert the repository name to lowercase for Docker tag
      - name: Set lowercase repo name
        run: echo "LOWER_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ env.LOWER_REPO }}:${{ env.TAG }} --tag ghcr.io/${{ env.LOWER_REPO }}:latest

      # Log in to GitHub Container Registry manually
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ env.LOWER_REPO }}:${{ env.TAG }}
          docker push ghcr.io/${{ env.LOWER_REPO }}:latest
